app:
  name: Medium_uz
  # ////   For HEROKU
  host: "109.123.234.250:7007"
  # LOCAL
  # host: "localhost:"
  version: "1.0"

db:
  dbname: "quffklnl"
  host: "heffalump.db.elephantsql.com"
  port: "5432"
  sslmode: "disable"
  username: "quffklnl"

redis:
  host: "redis-16183.c257.us-east-1-3.ec2.cloud.redislabs.com"
  port: "16183"
  db: 0

smtp:
  host: smtp.gmail.com
  port: 587
  senderEmail: phapp0224mb@gmail.com
