port: '8080'

db:
  dbname: mediumuz
  host: localhost
  port: '2001'
  sslmode: disable
  username: postgres

redis:
  host: localhost
  port: '6379'
  db: 0

smtp:
  host: smtp.gmail.com
  port: 587
  senderEmail: phapp0224mb@gmail.com
