app:
  name: Medium_uz
  host: "localhost:"
  port: "5000"
  version: "1.0"

db:
  dbname: "dd3jlput8sprfr"
  host: "ec2-35-168-194-15.compute-1.amazonaws.com"
  port: "5432"
  sslmode: "require"
  username: "enfmdlgvbodjvj"

redis:
  host: "redis-10231.c61.us-east-1-3.ec2.cloud.redislabs.com"
  port: "10231"
  db: 0

smtp:
  host: smtp.gmail.com
  port: 587
  senderEmail: phapp0224mb@gmail.com
