app:
  name: Medium_uz
  host: "localhost:"
  port: "8080"
  version: "1.0"

db:
  dbname: "dd3jlput8sprfr"
  host: "ec2-35-168-194-15.compute-1.amazonaws.com"
  port: "5432"
  sslmode: "require"
  username: "enfmdlgvbodjvj"

redis:
  host: localhost
  port: "6379"
  db: 0

smtp:
  host: smtp.gmail.com
  port: 587
  senderEmail: phapp0224mb@gmail.com
