app:
  name: Medium_uz
  #////   For HEROKU
  host: "mediumuz.herokuapp.com"
  # host: "localhost:"
  # port: "8080"
  version: "1.0"

db:
  dbname: "quffklnl"
  host: "heffalump.db.elephantsql.com"
  port: "5432"
  sslmode: "disable"
  username: "quffklnl"

redis:
  host: "redis-10231.c61.us-east-1-3.ec2.cloud.redislabs.com"
  port: "10231"
  db: 0

smtp:
  host: smtp.gmail.com
  port: 587
  senderEmail: phapp0224mb@gmail.com
