basePath: /
definitions:
  error.errorResponse:
    properties:
      message:
        type: string
    type: object
  error.errorResponseData:
    properties:
      data: {}
      message:
        type: string
    type: object
  model.Post:
    properties:
      image:
        type: string
      tags:
        items:
          type: string
        type: array
      text:
        default: Hello World
        type: string
      title:
        default: Tutorial Golang
        type: string
    type: object
  model.ResponseSign:
    properties:
      id:
        type: integer
      token:
        type: string
    type: object
  model.ResponseSuccess:
    properties:
      data: {}
      message:
        type: string
    type: object
  model.SignInInput:
    properties:
      email:
        default: phapp0224mb@gmail.com
        type: string
      password:
        default: 0224mb
        type: string
    type: object
  model.User:
    properties:
      bio:
        default: I am Golang dev
        type: string
      city:
        default: Navoi
        type: string
      email:
        default: phapp0224mb@gmail.com
        type: string
      first_name:
        default: MRB
        type: string
      interesting:
        items:
          type: string
        type: array
      nickname:
        default: mrb
        type: string
      password:
        default: 0224mb
        type: string
      phone:
        default: +9989 93 753 65 71
        type: string
      second_name:
        default: HERO
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: phapp0224mb@gmail.com
    name: Bakhodir Yashin Mansur
  description: API Server for MediumuZ Application
  termsOfService: https://github.com/BakhodiribnYashinibnMansur/Medium_uz
  title: MediumuZ API
  version: "1.0"
paths:
  /api/account/get:
    get:
      consumes:
      - application/json
      description: return account data. if you send id = "" or null return current
        user data. if send id = number return number user data .
      operationId: get-account
      parameters:
      - description: id
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get Account Data
      tags:
      - Account
  /api/account/recovery:
    get:
      consumes:
      - application/json
      description: send code for  Recovery Password
      operationId: recovery-password-send-code
      parameters:
      - description: email
        in: query
        name: email
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      summary: Send code for  Recovery Password
      tags:
      - Auth
  /api/account/recovery-password:
    get:
      consumes:
      - application/json
      description: Recovery Password
      operationId: recovery-password
      parameters:
      - description: password
        in: query
        name: password
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      summary: Recovery Password
      tags:
      - Auth
  /api/account/recovery-verify:
    get:
      consumes:
      - application/json
      description: check code for  Recovery Password
      operationId: recovery-code-email
      parameters:
      - description: code
        in: query
        name: code
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      summary: Check code for  Recovery Password
      tags:
      - Auth
  /api/account/sendcode:
    get:
      consumes:
      - application/json
      description: send code to email for  verification
      operationId: send-code-email
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Send code for  Verification Email
      tags:
      - Account
  /api/account/update:
    put:
      consumes:
      - application/json
      description: update account give data
      operationId: update-account
      parameters:
      - description: account info
        in: body
        name: input
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update Account
      tags:
      - Account
  /api/account/upload-image:
    patch:
      consumes:
      - application/json
      - multipart/form-data
      description: Upload Account Image
      operationId: upload-image
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      - application/octet-stream
      - image/png
      - image/jpeg
      - image/jpg
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Upload Account Image
      tags:
      - Account
  /api/account/verify:
    get:
      consumes:
      - application/json
      description: verification email with code
      operationId: verify-email
      parameters:
      - description: code
        in: query
        name: code
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Verification Email
      tags:
      - Account
  /api/post/create:
    post:
      consumes:
      - application/json
      description: create post
      operationId: create-post
      parameters:
      - description: post info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.Post'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create Post
      tags:
      - Post
  /api/post/get/{id}:
    get:
      consumes:
      - application/json
      description: get post by id
      operationId: get-post-id
      parameters:
      - description: Param ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get  Post By ID
      tags:
      - Post
  /api/post/upload-image:
    patch:
      consumes:
      - application/json
      - multipart/form-data
      description: Upload Post Image
      operationId: upload-image-post
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      - description: code
        in: query
        name: id
        type: integer
      produces:
      - application/json
      - application/octet-stream
      - image/png
      - image/jpeg
      - image/jpg
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Upload Post Image
      tags:
      - Post
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login account
      operationId: login-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSign'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      summary: SignIn
      tags:
      - Auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSign'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      summary: SignUp
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
