basePath: /
definitions:
  error.errorResponse:
    properties:
      message:
        type: string
    type: object
  error.errorResponseData:
    properties:
      data: {}
      message:
        type: string
    type: object
  model.ResponseSign:
    properties:
      id:
        type: integer
      token:
        type: string
    type: object
  model.ResponseSuccess:
    properties:
      data: {}
      message:
        type: string
    type: object
  model.SignInInput:
    properties:
      password:
        default: 0224mb
        type: string
      username:
        default: MRB
        type: string
    type: object
  model.User:
    properties:
      bio:
        default: I am Golang dev
        type: string
      city:
        default: Navoi
        type: string
      email:
        default: phapp0224mb@gmail.com
        type: string
      first_name:
        default: MRB
        type: string
      image:
        type: string
      interesting:
        items:
          type: string
        type: array
      nickname:
        default: mrb
        type: string
      password:
        default: 0224mb
        type: string
      phone:
        default: +9989 93 753 65 71
        type: string
      second_name:
        default: HERO
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: phapp0224mb@gmail.com
    name: Bakhodir Yashin Mansur
  description: API Server for MediumuZ Application
  termsOfService: https://github.com/BakhodiribnYashinibnMansur/Medium_uz
  title: MediumuZ API
  version: "1.0"
paths:
  /api/account/resend:
    get:
      consumes:
      - application/json
      description: resend code to email for  verification
      operationId: resend-code-email
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Resend cod for  Verification Email
      tags:
      - Account
  /api/account/upload-image:
    post:
      consumes:
      - application/json
      - multipart/form-data
      description: Upload Account Image
      operationId: upload-image
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      - application/octet-stream
      - image/png
      - image/jpeg
      - image/jpg
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Upload Account Image
      tags:
      - Account
  /api/account/verify:
    get:
      consumes:
      - application/json
      description: verification email with code
      operationId: verify-email
      parameters:
      - description: code
        in: query
        name: code
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Verification Email
      tags:
      - Account
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login account
      operationId: login-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSign'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      summary: SignIn
      tags:
      - Auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseSign'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error.errorResponseData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/error.errorResponse'
      summary: SignUp
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
